services:
  domus_database:
    image: postgres
    container_name: domus_database
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: app_user
      POSTGRES_DB: app_db
      POSTGRES_PASSWORD: app_password
    ports:
      - "127.0.0.1:5432:5432"

  domus_app:
    image: ghcr.io/kaiquepy/domus_backend:main
    container_name: domus_backend
    depends_on:
      - domus_database
    environment:
      DATABASE_URL: postgresql+psycopg://app_user:app_password@domus_database:5432/app_db

  watchtower:
    image: containrrr/watchtower
    container_name: domus_watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    command: --interval 30

networks:
  default:
    external: true
    name: proxy_network

volumes:
  pgdata:
