services:
  domus_database:
    image: postgres
    container_name: domus_database
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: app_user
      POSTGRES_DB: app_db
      POSTGRES_PASSWORD: app_password
    expose:
      - 5432
    networks:
      - backend
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "app_user"]
      interval: 10s
      timeout: 5s
      retries: 5

  domus_app:
    image: ghcr.io/kaiquepy/domus_backend:main
    container_name: domus_backend
    restart: always
    depends_on:
      domus_database:
        condition: service_healthy
    networks:
      - backend
      - frontend
    expose:
      - 3000
    environment:
      DATABASE_URL: postgresql+psycopg://app_user:app_password@domus_database:5432/app_db

  watchtower:
    image: containrrr/watchtower
    container_name: domus_watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    command: --interval 30

networks:
  frontend:
    external: true
    name: proxy_network
  backend:
    driver: bridge

volumes:
  pgdata:
